volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    env_file: .env
    image: postgres:13.10
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: username0416/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media:/app/media

  frontend:
    image: username0416/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - backend

  nginx:
    image: username0416/foodgram_gateway
    env_file: .env
    depends_on:
      - frontend
    volumes:
      - static_volume:/staticfiles/
      - media:/app/media
    ports:
      - 8000:80
