# Generated by Django 4.2.16 on 2024-12-30 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username может содержать только буквы,цифры и символы: . @ + - _', regex='^[\\w.@+-]+$')], verbose_name='Логин'),
        ),
    ]
